// frontend/taro-app/packages/core/src/components/KratosTabBar.tsx
import { Image, Text, View } from '@tarojs/components'
import { resolveModuleIcon, resolveStaticView } from '../module'
import { APP_MENU_ROOT_ID, navigateAppRoute, useAppMenuBadges, useAppNavigation } from '../navigation'
import { useI18n } from '../locales'
import { resolveRootMenuId } from '../navigation-tree.mjs'
import './KratosTabBar.scss'

/** 自绘 TabBar 参数。 */
export interface KratosTabBarProps {
  route: string
}

/** 根据动态菜单显示的自绘 TabBar。 */
export function KratosTabBar({ route }: KratosTabBarProps) {
  const menus = useAppNavigation((state) => state.menus)
  const tabBar = useAppNavigation((state) => state.tabBar)
  const { t } = useI18n()

  /** 按稳定 viewKey 优先取界面语言标签，未配置的菜单回退后端标题。 */
  const tabBarTitleKeys: Record<string, string> = {
    HOME: 'core.navigation.home',
    APP_ANALYTIC: 'core.navigation.analytics',
    APP_REPORT: 'core.navigation.report',
    MESSAGE_INBOX: 'core.navigation.message',
    PROFILE_HOME: 'core.navigation.my',
  }
  const tabBarTitle = (item: { viewKey: string; title: string }): string =>
    (tabBarTitleKeys[item.viewKey] ? t(tabBarTitleKeys[item.viewKey]) : '') || item.title
  const messageBadge = useAppMenuBadges((state) => state.badges.MESSAGE_INBOX ?? 0)
  const routeMenu = menus.find((menu) => resolveStaticView(menu.viewKey) === route)
  const tabMenuId = routeMenu
    ? resolveRootMenuId(menus, routeMenu.id, APP_MENU_ROOT_ID)
    : undefined
  const activeMenu = tabBar.find((menu) => menu.id === tabMenuId)
  if (!activeMenu || !tabBar.length) return null

  return (
    <View className='kratos-tab-bar'>
      {tabBar.map((item) => {
        const active = activeMenu.id === item.id
        const icon = resolveModuleIcon(active && item.selectedIcon ? item.selectedIcon : item.icon)
        return (
          <View
            key={item.id}
            className='kratos-tab-bar__item'
            onClick={() => navigateAppRoute(item.path)}
          >
            {icon ? (
              <Image className='kratos-tab-bar__icon' src={icon} mode='aspectFit' />
            ) : null}
            {!icon && item.viewKey === 'MESSAGE_INBOX' ? (
              <View className={`kratos-tab-bar__message-icon${active ? ' kratos-tab-bar__message-icon--active' : ''}`} />
            ) : null}
            {item.viewKey === 'MESSAGE_INBOX' && messageBadge ? (
              <View className='kratos-tab-bar__badge' aria-hidden='true' />
            ) : null}
            <Text className={active ? 'kratos-tab-bar__text--active' : ''}>{tabBarTitle(item)}</Text>
          </View>
        )
      })}
    </View>
  )
}

export default KratosTabBar

// frontend/uni-app/packages/core/src/components/KratosTabBar.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { resolveModuleIcon, resolveStaticView } from '../module'
import { APP_MENU_ROOT_ID, useAppMenuBadge, useAppNavigation } from '../navigation'
import { useI18n } from '../locales'
import { resolveRootMenuId } from '../navigation-tree.mjs'

const props = defineProps<{ route: string }>()
const { menus, tabBar, navigate } = useAppNavigation()
const { t } = useI18n()

/** 按稳定 viewKey 优先取界面语言标签，未配置的菜单回退后端标题。 */
const tabBarTitleKeys: Record<string, string> = {
  HOME: 'core.navigation.home',
  APP_ANALYTIC: 'core.navigation.analytics',
  APP_REPORT: 'core.navigation.report',
  MESSAGE_INBOX: 'core.navigation.message',
  PROFILE_HOME: 'core.navigation.my',
}
const tabBarTitle = (item: { viewKey: string; title: string }): string =>
  (tabBarTitleKeys[item.viewKey] ? t(tabBarTitleKeys[item.viewKey]) : '') || item.title
const activeMenu = computed(() => {
  const routeMenu = menus.value.find((menu) => resolveStaticView(menu.viewKey) === props.route)
  if (!routeMenu) return
  const tabMenuId = resolveRootMenuId(menus.value, routeMenu.id, APP_MENU_ROOT_ID)
  return tabBar.value.find((menu) => menu.id === tabMenuId)
})
const visible = computed(() => Boolean(activeMenu.value && tabBar.value.length))
const messageBadge = useAppMenuBadge('MESSAGE_INBOX')
// #ifdef H5
// H5 端 tabBar.custom 不隐藏内置 tabbar,需手动隐藏,否则其边线从自定义栏上方露出形成双线。
onMounted(() => {
  uni.hideTabBar({ fail: () => {} })
})
// #endif
</script>

<template>
  <view v-if="visible" class="kratos-tab-bar">
    <view
      v-for="item in tabBar"
      :key="item.id"
      class="kratos-tab-bar__item"
      @tap="navigate(item.path)"
    >
      <view
        v-if="item.viewKey === 'MESSAGE_INBOX' && messageBadge"
        class="kratos-tab-bar__badge"
        aria-hidden="true"
      />
      <image
        v-if="resolveModuleIcon(item.icon)"
        class="kratos-tab-bar__icon"
        :src="
          resolveModuleIcon(
            activeMenu?.id === item.id && item.selectedIcon ? item.selectedIcon : item.icon,
          )
        "
        mode="aspectFit"
      />
      <view
        v-else-if="item.viewKey === 'MESSAGE_INBOX'"
        class="kratos-tab-bar__message-icon"
        :class="{ 'kratos-tab-bar__message-icon--active': activeMenu?.id === item.id }"
        aria-hidden="true"
      />
      <text :class="{ 'kratos-tab-bar__text--active': activeMenu?.id === item.id }">
        {{ tabBarTitle(item) }}
      </text>
    </view>
  </view>
</template>

<style scoped>
.kratos-tab-bar {
  --kratos-tab-bar-color: #333;
  --kratos-tab-bar-active-color: #27ba9b;

  position: fixed;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 999;
  box-sizing: border-box;
  display: flex;
  height: calc(48px + env(safe-area-inset-bottom));
  padding-bottom: env(safe-area-inset-bottom);
  border-top: 1px solid #eee;
  background: #fff;
}
.kratos-tab-bar__item {
  position: relative;
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  transform: translateY(clamp(1px, env(safe-area-inset-bottom), 7px));
  color: var(--kratos-tab-bar-color);
  font-size: 10px;
  line-height: 12px;
}
.kratos-tab-bar__icon {
  width: 28px;
  height: 28px;
  margin-bottom: 4px;
}
.kratos-tab-bar__message-icon {
  position: relative;
  width: 22px;
  height: 18px;
  margin-bottom: 6px;
  border: 2px solid var(--kratos-tab-bar-color);
  border-radius: 6px;
  box-sizing: border-box;
}
.kratos-tab-bar__message-icon::before {
  position: absolute;
  top: 5px;
  left: 4px;
  width: 3px;
  height: 3px;
  border-radius: 50%;
  background: var(--kratos-tab-bar-color);
  box-shadow:
    5px 0 var(--kratos-tab-bar-color),
    10px 0 var(--kratos-tab-bar-color);
  content: '';
}
.kratos-tab-bar__message-icon::after {
  position: absolute;
  bottom: -5px;
  left: 3px;
  width: 7px;
  height: 7px;
  border-right: 2px solid var(--kratos-tab-bar-color);
  border-bottom: 2px solid var(--kratos-tab-bar-color);
  background: #fff;
  content: '';
  transform: rotate(45deg);
}
.kratos-tab-bar__message-icon--active {
  border-color: var(--kratos-tab-bar-active-color);
}
.kratos-tab-bar__message-icon--active::before {
  background: var(--kratos-tab-bar-active-color);
  box-shadow:
    5px 0 var(--kratos-tab-bar-active-color),
    10px 0 var(--kratos-tab-bar-active-color);
}
.kratos-tab-bar__message-icon--active::after {
  border-color: var(--kratos-tab-bar-active-color);
}
.kratos-tab-bar__text--active {
  color: var(--kratos-tab-bar-active-color);
}
.kratos-tab-bar__badge {
  position: absolute;
  top: 0;
  right: calc(50% - 19px);
  width: 10px;
  height: 10px;
  box-sizing: border-box;
  border: 2px solid #fff;
  border-radius: 50%;
  background: #e5484d;
}
</style>
