// frontend/uni-app/packages/modules/system/src/views/pagesMember/ai/components/Composer.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { AiAttachment } from '../../../../rpc/base/v1/ai_session'
import type { AiProviderModelOption } from '../../../../rpc/base/v1/ai_provider'

type InputEventValue = {
  detail: {
    value: string
  }
}

const props = defineProps<{
  modelValue: string
  attachments: AiAttachment[]
  /** 当前可供选择的供应商与模型。 */
  modelProviders: AiProviderModelOption[]
  /** 当前选中的供应商编号和模型名称。 */
  providerId: number
  modelName: string
  providerPlaceholder: string
  modelPlaceholder: string
  placeholder: string
  bottom: string
  recording: boolean
  sending: boolean
  disabled: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
  attach: []
  record: []
  send: []
  'remove-attachment': [attachment: AiAttachment]
  'model-change': [providerId: number, modelName: string]
}>()

const providerNames = computed(() => props.modelProviders.map((provider) => provider.name))
const selectedProvider = computed(() =>
  props.modelProviders.find((provider) => provider.provider_id === props.providerId),
)
const modelNames = computed(() => selectedProvider.value?.models ?? [])
const providerIndex = computed(() =>
  Math.max(
    props.modelProviders.findIndex((provider) => provider.provider_id === props.providerId),
    0,
  ),
)
const modelIndex = computed(() => Math.max(modelNames.value.indexOf(props.modelName), 0))

function handleInput(event: Event) {
  emit('update:modelValue', ((event as unknown as InputEventValue).detail?.value || '').toString())
}

function handleProviderChange(event: { detail: { value: number | string } }) {
  const provider = props.modelProviders[Number(event.detail.value)]
  emit('model-change', provider?.provider_id ?? 0, provider?.models[0] ?? '')
}

function handleModelChange(event: { detail: { value: number | string } }) {
  emit('model-change', props.providerId, modelNames.value[Number(event.detail.value)] ?? '')
}
</script>

<template>
  <view class="composer" :style="{ paddingBottom: bottom }">
    <view class="composer-model-selectors">
      <picker
        mode="selector"
        :range="providerNames"
        :value="providerIndex"
        :disabled="sending || !modelProviders.length"
        @change="handleProviderChange"
      >
        <view class="composer-model-select">{{
          selectedProvider?.name || providerPlaceholder
        }}</view>
      </picker>
      <picker
        mode="selector"
        :range="modelNames"
        :value="modelIndex"
        :disabled="sending || !modelNames.length"
        @change="handleModelChange"
      >
        <view class="composer-model-select">{{ modelName || modelPlaceholder }}</view>
      </picker>
    </view>
    <view class="composer-main">
      <button class="attach-button" hover-class="none" @tap="emit('attach')">
        <uni-icons type="plusempty" size="30" color="#111" />
      </button>
      <view class="composer-card">
        <view v-if="attachments.length" class="composer-attachments">
          <view
            v-for="attachment in attachments"
            :key="attachment.id || attachment.url || attachment.name"
            class="composer-attachment"
            @tap="emit('remove-attachment', attachment)"
          >
            {{ attachment.name }} ×
          </view>
        </view>
        <textarea
          class="composer-input"
          auto-height
          :maxlength="500"
          :value="modelValue"
          :placeholder="placeholder"
          placeholder-class="composer-placeholder"
          @input="handleInput"
        />
        <button
          class="voice-button"
          :class="{ active: recording }"
          hover-class="none"
          @tap="emit('record')"
        >
          <uni-icons type="mic" size="28" :color="recording ? '#00a96b' : '#111'" />
        </button>
      </view>
      <button
        class="send-button"
        :class="{ 'is-disabled': disabled, 'is-sending': sending }"
        :disabled="disabled"
        hover-class="none"
        @tap="emit('send')"
      >
        <uni-icons type="paperplane" size="28" :color="disabled ? '#111' : '#00a96b'" />
      </button>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.attach-button,
.voice-button,
.send-button {
  padding: 0;
  margin: 0;
  border-radius: 0;
  background: transparent;
  line-height: normal;

  &::after {
    border: none;
  }
}

.composer {
  flex-shrink: 0;
  width: 100%;
  padding: 14rpx 24rpx 18rpx;
  overflow: hidden;
  background-color: transparent;
  box-sizing: border-box;
}

.composer-main {
  display: flex;
  align-items: center;
  gap: 16rpx;
  min-height: 124rpx;
  padding: 22rpx 18rpx;
  border-radius: 24rpx;
  background-color: #fff;
  box-shadow: 0 12rpx 34rpx rgba(15, 23, 42, 0.08);
  box-sizing: border-box;
}

.composer-model-selectors {
  display: flex;
  justify-content: flex-end;
  gap: 12rpx;
  min-width: 0;
  margin: 0 8rpx 12rpx;
}

.composer-model-select {
  max-width: 300rpx;
  min-width: 120rpx;
  padding: 8rpx 16rpx;
  overflow: hidden;
  color: #46515b;
  font-size: 22rpx;
  line-height: 32rpx;
  text-overflow: ellipsis;
  white-space: nowrap;
  background: #fff;
  border: 2rpx solid #d6dae2;
  border-radius: 8rpx;
}

.attach-button {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 72rpx;
  height: 72rpx;
  border: 2rpx solid #d6dae2;
  border-radius: 50%;
  background-color: #fff;
  box-shadow: none;
  box-sizing: border-box;
}

.composer-card {
  flex: 1;
  min-width: 0;
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 10rpx;
  min-height: 72rpx;
  padding: 0 12rpx 0 28rpx;
  border: 2rpx solid #d6dae2;
  border-radius: 38rpx;
  background-color: #fff;
  box-shadow: none;
  box-sizing: border-box;
}

.composer-attachments {
  display: flex;
  flex-wrap: wrap;
  gap: 8rpx;
  width: 100%;
  padding-top: 4rpx;
}

.composer-attachment {
  max-width: 240rpx;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  padding: 6rpx 12rpx;
  border-radius: 8rpx;
  color: #16806d;
  font-size: 20rpx;
  line-height: 28rpx;
  background-color: #e8f8f4;
}

.composer-input {
  flex: 1;
  min-width: 0;
  min-height: 42rpx;
  max-height: 126rpx;
  padding: 14rpx 0;
  box-sizing: border-box;
  color: #333;
  font-size: 29rpx;
  line-height: 42rpx;
  overflow-y: auto;
  background-color: transparent;
}

.composer-placeholder {
  color: #8d929c;
  font-size: 29rpx;
}

.voice-button,
.send-button {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
}

.voice-button {
  width: 60rpx;
  height: 60rpx;
  background-color: transparent;
}

.voice-button.active {
  background-color: #e8f8f4;
}

.send-button {
  width: 74rpx;
  height: 74rpx;
  background-color: #f2f2f2;
}

.send-button.is-disabled {
  background-color: #f2f2f2;
}

.send-button:not(.is-disabled) {
  background-color: #e7f7f2;
}
</style>

// frontend/taro-app/packages/modules/system/src/views/pagesMember/ai/components/Composer.tsx
import { Button, Picker, Text, Textarea, View } from '@tarojs/components'
import { UniIcon } from '@liujitcn/kratos-taro-app-ui'
import type { AiAttachment } from '../../../../rpc/base/v1/ai_session'
import type { AiProviderModelOption } from '../../../../rpc/base/v1/ai_provider'
import './composer.scss'

/** AI 助手输入框与模型选择器参数。 */
type ComposerProps = {
  value: string
  attachments: AiAttachment[]
  /** 当前可供选择的供应商与模型。 */
  modelProviders: AiProviderModelOption[]
  /** 当前选中的供应商编号和模型名称。 */
  providerId: number
  modelName: string
  /** 选择器未配置时显示的本地化占位文字。 */
  providerPlaceholder: string
  modelPlaceholder: string
  placeholder: string
  bottom: string
  recording: boolean
  sending: boolean
  disabled: boolean
  onChange: (value: string) => void
  onAttach: () => void
  onRecord: () => void
  onSend: () => void
  onRemoveAttachment: (attachment: AiAttachment) => void
  onModelChange: (providerId: number, modelName: string) => void
}

/** AI 助手消息输入器。 */
export default function Composer(props: ComposerProps) {
  const selectedProvider = props.modelProviders.find((provider) => provider.provider_id === props.providerId)
  const modelNames = selectedProvider?.models ?? []
  const providerIndex = Math.max(props.modelProviders.findIndex((provider) => provider.provider_id === props.providerId), 0)
  const modelIndex = Math.max(modelNames.indexOf(props.modelName), 0)

  return (
    <View className='composer' style={{ paddingBottom: props.bottom }}>
      <View className='composer-model-selectors'>
        <Picker
          mode='selector'
          range={props.modelProviders.map((provider) => provider.name)}
          value={providerIndex}
          disabled={props.sending || !props.modelProviders.length}
          onChange={(event) => {
            const provider = props.modelProviders[Number(event.detail.value)]
            props.onModelChange(provider?.provider_id ?? 0, provider?.models[0] ?? '')
          }}
        >
          <View className='composer-model-select'><Text>{selectedProvider?.name || props.providerPlaceholder}</Text></View>
        </Picker>
        <Picker
          mode='selector'
          range={modelNames}
          value={modelIndex}
          disabled={props.sending || !modelNames.length}
          onChange={(event) => props.onModelChange(props.providerId, modelNames[Number(event.detail.value)] ?? '')}
        >
          <View className='composer-model-select'><Text>{props.modelName || props.modelPlaceholder}</Text></View>
        </Picker>
      </View>
      <View className='composer-main'>
        <Button className='attach-button' hoverClass='none' onClick={props.onAttach}>
          <UniIcon type='plusempty' size={30} color='#111' />
        </Button>
        <View className='composer-card'>
          {props.attachments.length ? (
            <View className='composer-attachments'>
              {props.attachments.map((attachment) => (
                <View
                  key={attachment.id || attachment.url || attachment.name}
                  className='composer-attachment'
                  onClick={() => props.onRemoveAttachment(attachment)}
                >
                  <Text>{attachment.name} ×</Text>
                </View>
              ))}
            </View>
          ) : null}
          <Textarea
            className='composer-input'
            autoHeight
            maxlength={500}
            value={props.value}
            placeholder={props.placeholder}
            placeholderClass='composer-placeholder'
            onInput={(event) => props.onChange(event.detail.value)}
          />
          <Button
            className={`voice-button${props.recording ? ' active' : ''}`}
            hoverClass='none'
            onClick={props.onRecord}
          >
            <UniIcon type='mic' size={28} color={props.recording ? '#00a96b' : '#111'} />
          </Button>
        </View>
        <Button
          className={`send-button${props.disabled ? ' is-disabled' : ''}${props.sending ? ' is-sending' : ''}`}
          disabled={props.disabled}
          hoverClass='none'
          onClick={props.onSend}
        >
          <UniIcon type='paperplane' size={28} color={props.disabled ? '#111' : '#00a96b'} />
        </Button>
      </View>
    </View>
  )
}
