// frontend/taro-app/apps/taro-app/src/pages/bootstrap/index.tsx
import Taro, { useLoad } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { resolveStaticView } from '@liujitcn/kratos-taro-app-core'

/** 固定启动页，模块注册完成后进入启动状态页。 */
export default function BootstrapPage() {
  useLoad((options) => {
    const route = resolveStaticView('BOOTSTRAP_LOADING') ?? 'pages/status/index'
    const target = options?.route ? decodeURIComponent(options.route) : 'app/home'
    void Taro.reLaunch({
      url: `/${route}?state=BOOTSTRAP_LOADING&bootstrap=1&route=${encodeURIComponent(target)}`,
    })
  })
  return <View />
}

// frontend/app/apps/app/src/pages/bootstrap/index.vue
<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { resolveStaticView } from '@liujitcn/kratos-app-core'

onLoad((options) => {
  const route = resolveStaticView('BOOTSTRAP_LOADING') ?? 'pages/status/index'
  const target = options?.route ? decodeURIComponent(options.route) : 'app/home'
  uni.reLaunch({
    url: `/${route}?state=BOOTSTRAP_LOADING&bootstrap=1&route=${encodeURIComponent(target)}`,
  })
})
</script>

<template>
  <view />
</template>
