// frontend/taro-app/packages/core/src/views/pages/status/index.tsx
import { useLoad } from '@tarojs/taro'
import { useState } from 'react'
import BootstrapStatus from '../../../components/BootstrapStatus'
import {
  initializeAppNavigation,
  launchAppStatus,
  navigateAppRoute,
} from '../../../navigation'
import type { BootstrapViewKey } from '../../../module'
import { useI18n } from '../../../locales'

/** 启动与错误状态页。 */
export default function StatusPage() {
  const { t } = useI18n()
  const [state, setState] = useState<BootstrapViewKey>('BOOTSTRAP_LOADING')
  const [detail, setDetail] = useState('')

  useLoad((options) => {
    const nextState = (options?.state as BootstrapViewKey | undefined) ?? 'BOOTSTRAP_LOADING'
    setState(nextState)
    setDetail(options?.detail ? decodeURIComponent(options.detail) : '')
    if (options?.bootstrap !== '1') return
    void initializeAppNavigation()
      .then(() => {
        navigateAppRoute(options?.route ? decodeURIComponent(options.route) : 'app/home', {
          replace: true,
        })
      })
      .catch((error: unknown) => {
        launchAppStatus('CONFIG_ERROR', error instanceof Error ? error.message : String(error))
      })
  })

  const title = state === 'BOOTSTRAP_LOADING' ? t('core.status.loading') : t(`core.status.${state}`)
  return <BootstrapStatus title={title} detail={detail} />
}

// frontend/uni-app/packages/core/src/views/pages/status/index.vue
<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { computed, ref } from 'vue'
import BootstrapStatus from '../../../components/BootstrapStatus.vue'
import { initializeAppNavigation, launchAppStatus, navigateAppRoute } from '../../../navigation'
import type { BootstrapViewKey } from '../../../module'
import { useI18n } from '../../../locales'

const state = ref<BootstrapViewKey>('BOOTSTRAP_LOADING')
const detail = ref('')
const { t } = useI18n()
const stateTitle = computed(() =>
  state.value === 'BOOTSTRAP_LOADING' ? t('core.status.loading') : t(`core.status.${state.value}`),
)

onLoad((options) => {
  state.value = (options?.state as BootstrapViewKey | undefined) ?? 'BOOTSTRAP_LOADING'
  detail.value = options?.detail ? decodeURIComponent(options.detail) : ''
  if (options?.bootstrap !== '1') return
  void initializeAppNavigation()
    .then(() => {
      navigateAppRoute(options?.route ? decodeURIComponent(options.route) : 'app/home', {
        replace: true,
      })
    })
    .catch((error) => {
      launchAppStatus('CONFIG_ERROR', error instanceof Error ? error.message : String(error))
    })
})
</script>

<template>
  <BootstrapStatus :title="stateTitle" :detail="detail" />
</template>
