// frontend/app/packages/core/src/components/BootstrapStatus.vue
<script setup lang="ts">
defineProps<{ title?: string; detail?: string }>()
</script>

<template>
  <view class="bootstrap-status">
    <image class="bootstrap-status__logo" src="../static/images/logo_icon.png" mode="aspectFit" />
    <text class="bootstrap-status__title">{{ title || '正在加载' }}</text>
    <text v-if="detail" class="bootstrap-status__detail">{{ detail }}</text>
  </view>
</template>

<style scoped>
.bootstrap-status {
  display: flex;
  min-height: 100vh;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  padding: 48rpx;
  background: #f8f8f8;
  box-sizing: border-box;
}
.bootstrap-status__logo {
  width: 112rpx;
  height: 112rpx;
  margin-bottom: 32rpx;
}
.bootstrap-status__title {
  color: #222;
  font-size: 32rpx;
}
.bootstrap-status__detail {
  margin-top: 16rpx;
  color: #777;
  font-size: 24rpx;
  text-align: center;
}
</style>

// frontend/taro-app/packages/core/src/components/BootstrapStatus.tsx
import { Image, Text, View } from '@tarojs/components'
import './BootstrapStatus.scss'

/** 启动状态组件参数。 */
export interface BootstrapStatusProps {
  title?: string
  detail?: string
}

/** 全屏启动状态。 */
export function BootstrapStatus({ title, detail }: BootstrapStatusProps) {
  return (
    <View className='bootstrap-status'>
      <Image
        className='bootstrap-status__logo'
        src='/static/images/logo_icon.png'
        mode='aspectFit'
      />
      <Text className='bootstrap-status__title'>{title || '正在加载'}</Text>
      {detail ? <Text className='bootstrap-status__detail'>{detail}</Text> : null}
    </View>
  )
}

export default BootstrapStatus
