// frontend/app/packages/core/src/components/KratosTabBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { resolveModuleIcon, resolveStaticView } from '../module'
import { APP_MENU_ROOT_ID, useAppNavigation } from '../navigation'
import { resolveRootMenuId } from '../navigation-tree.mjs'

const props = defineProps<{ route: string }>()
const { menus, tabBar, navigate } = useAppNavigation()
const activeMenu = computed(() => {
  const routeMenu = menus.value.find((menu) => resolveStaticView(menu.viewKey) === props.route)
  if (!routeMenu) return
  const tabMenuId = resolveRootMenuId(menus.value, routeMenu.id, APP_MENU_ROOT_ID)
  return tabBar.value.find((menu) => menu.id === tabMenuId)
})
const visible = computed(() => Boolean(activeMenu.value && tabBar.value.length))
</script>

<template>
  <view v-if="visible" class="kratos-tab-bar">
    <view
      v-for="item in tabBar"
      :key="item.id"
      class="kratos-tab-bar__item"
      @tap="navigate(item.path)"
    >
      <image
        v-if="resolveModuleIcon(item.icon)"
        class="kratos-tab-bar__icon"
        :src="
          resolveModuleIcon(
            activeMenu?.id === item.id && item.selectedIcon ? item.selectedIcon : item.icon,
          )
        "
        mode="aspectFit"
      />
      <text :class="{ 'kratos-tab-bar__text--active': activeMenu?.id === item.id }">
        {{ item.title }}
      </text>
    </view>
  </view>
</template>

<style scoped>
.kratos-tab-bar {
  position: fixed;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 999;
  display: flex;
  min-height: 100rpx;
  padding-bottom: env(safe-area-inset-bottom);
  border-top: 1px solid #eee;
  background: #fff;
}
.kratos-tab-bar__item {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  color: #333;
  font-size: 24rpx;
}
.kratos-tab-bar__icon {
  width: 42rpx;
  height: 42rpx;
  margin-bottom: 4rpx;
}
.kratos-tab-bar__text--active {
  color: #27ba9b;
}
</style>

// frontend/taro-app/packages/core/src/components/KratosTabBar.tsx
import { Image, Text, View } from '@tarojs/components'
import { resolveModuleIcon, resolveStaticView } from '../module'
import { APP_MENU_ROOT_ID, navigateAppRoute, useAppNavigation } from '../navigation'
import { resolveRootMenuId } from '../navigation-tree.mjs'
import './KratosTabBar.scss'

/** 自绘 TabBar 参数。 */
export interface KratosTabBarProps {
  route: string
}

/** 根据动态菜单显示的自绘 TabBar。 */
export function KratosTabBar({ route }: KratosTabBarProps) {
  const menus = useAppNavigation((state) => state.menus)
  const tabBar = useAppNavigation((state) => state.tabBar)
  const routeMenu = menus.find((menu) => resolveStaticView(menu.viewKey) === route)
  const tabMenuId = routeMenu
    ? resolveRootMenuId(menus, routeMenu.id, APP_MENU_ROOT_ID)
    : undefined
  const activeMenu = tabBar.find((menu) => menu.id === tabMenuId)
  if (!activeMenu || !tabBar.length) return null

  return (
    <View className='kratos-tab-bar'>
      {tabBar.map((item) => {
        const active = activeMenu.id === item.id
        const icon = resolveModuleIcon(active && item.selectedIcon ? item.selectedIcon : item.icon)
        return (
          <View
            key={item.id}
            className='kratos-tab-bar__item'
            onClick={() => navigateAppRoute(item.path)}
          >
            {icon ? (
              <Image className='kratos-tab-bar__icon' src={icon} mode='aspectFit' />
            ) : null}
            <Text className={active ? 'kratos-tab-bar__text--active' : ''}>{item.title}</Text>
          </View>
        )
      })}
    </View>
  )
}

export default KratosTabBar
